controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
handle_search:
    path: /search
    controller: App\Controller\SearchController::handleSerch
    methods: GET

app_home:
    path: /
    controller: App\Controller\HomeController::index
